### ISSUE TITLE
Problem using the reporter

### ISSUE THREAD

**Issue by w3apps** [jlogar/karma-nunit-reporter#2]
I'm having problems using the reporter. My karma conf file has:

reporters: ['progress', 'coverage', 'nunit'],

But when I run "karma start" I get:

 [WARN] reporter - Can not load "nunit"!
  TypeError: Cannot read property 'outputFile' of undefined
    at new NUnitReporter (xxx\node_modules\karma-nunit-reporter\index.js:8:26)

Am I missing something ?

**Comment by sebastianwolfmw** [comment]
Hi jlogar, where did things get up to with this?

It's a bit confusing having two versions of the same thing that are in different states of support/availability.

Would you be happy to either push the updated version to npm, or perhaps *not* do that, and close the repo in favour of Martin's?

**Comment by jlogar** [comment]
Haven't really been paying attention to the repo. I don't prefer either way.

If @martinmcwhorter is stil mainating his it would probably be better to just use his and close mine.

**Comment by martinmcwhorter** [comment]
Yes. If anyone has any pull requests, please make them against https://github.com/martinmcwhorter/karma-nunit2-reporter and I will be happy to merge fixes and features.

**Comment by jlogar** [comment]
Thank you, it's settled then. Will close this repo.

**Comment by Macadoshis** [comment]
@martinmcwhorter : "karma-nunit2-reporter works, but is incomplete. The xml is valid, but it is
missing the specific failed text-case reasons."

+1 !!

As a result Jenkins doesn't recognize a failed test as a fail but as a success...

**Comment by jlogar** [comment]
@Macadoshis please report in the karma-unit2-reporter. This repo is no longer maintained.

**Comment by martinmcwhorter** [comment]
@saad open up an issue in the karma-nunit2-reporter repository.
